// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/grpc/proto/limyedb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []float32              `protobuf:"fixed32,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        *Vector                `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	Payload       map[string]*Value      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Point) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *Point) GetPayload() map[string]*Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_NumberValue
	//	*Value_StringValue
	//	*Value_BoolValue
	//	*Value_ListValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,1,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,4,opt,name=list_value,json=listValue,proto3,oneof"`
}

func (*Value_NumberValue) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_ListValue) isValue_Kind() {}

type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{3}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type ScoredPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Vector        *Vector                `protobuf:"bytes,3,opt,name=vector,proto3" json:"vector,omitempty"`
	Payload       map[string]*Value      `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredPoint) Reset() {
	*x = ScoredPoint{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredPoint) ProtoMessage() {}

func (x *ScoredPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredPoint.ProtoReflect.Descriptor instead.
func (*ScoredPoint) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{4}
}

func (x *ScoredPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScoredPoint) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoredPoint) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *ScoredPoint) GetPayload() map[string]*Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HNSWConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	M              int32                  `protobuf:"varint,1,opt,name=m,proto3" json:"m,omitempty"`
	EfConstruction int32                  `protobuf:"varint,2,opt,name=ef_construction,json=efConstruction,proto3" json:"ef_construction,omitempty"`
	EfSearch       int32                  `protobuf:"varint,3,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HNSWConfig) Reset() {
	*x = HNSWConfig{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HNSWConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HNSWConfig) ProtoMessage() {}

func (x *HNSWConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HNSWConfig.ProtoReflect.Descriptor instead.
func (*HNSWConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{5}
}

func (x *HNSWConfig) GetM() int32 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *HNSWConfig) GetEfConstruction() int32 {
	if x != nil {
		return x.EfConstruction
	}
	return 0
}

func (x *HNSWConfig) GetEfSearch() int32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

type CollectionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimension     int32                  `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Metric        string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	OnDisk        bool                   `protobuf:"varint,4,opt,name=on_disk,json=onDisk,proto3" json:"on_disk,omitempty"`
	Hnsw          *HNSWConfig            `protobuf:"bytes,5,opt,name=hnsw,proto3" json:"hnsw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionConfig) Reset() {
	*x = CollectionConfig{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionConfig) ProtoMessage() {}

func (x *CollectionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionConfig.ProtoReflect.Descriptor instead.
func (*CollectionConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{6}
}

func (x *CollectionConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectionConfig) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CollectionConfig) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *CollectionConfig) GetOnDisk() bool {
	if x != nil {
		return x.OnDisk
	}
	return false
}

func (x *CollectionConfig) GetHnsw() *HNSWConfig {
	if x != nil {
		return x.Hnsw
	}
	return nil
}

type CollectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimension     int32                  `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Metric        string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Config        *CollectionConfig      `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionInfo) Reset() {
	*x = CollectionInfo{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfo) ProtoMessage() {}

func (x *CollectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfo.ProtoReflect.Descriptor instead.
func (*CollectionInfo) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{7}
}

func (x *CollectionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectionInfo) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CollectionInfo) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *CollectionInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CollectionInfo) GetConfig() *CollectionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CollectionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CollectionInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Filter:
	//
	//	*Filter_Must
	//	*Filter_Should
	//	*Filter_MustNot
	//	*Filter_Field
	Filter        isFilter_Filter `protobuf_oneof:"filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{8}
}

func (x *Filter) GetFilter() isFilter_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *Filter) GetMust() *MustFilter {
	if x != nil {
		if x, ok := x.Filter.(*Filter_Must); ok {
			return x.Must
		}
	}
	return nil
}

func (x *Filter) GetShould() *ShouldFilter {
	if x != nil {
		if x, ok := x.Filter.(*Filter_Should); ok {
			return x.Should
		}
	}
	return nil
}

func (x *Filter) GetMustNot() *MustNotFilter {
	if x != nil {
		if x, ok := x.Filter.(*Filter_MustNot); ok {
			return x.MustNot
		}
	}
	return nil
}

func (x *Filter) GetField() *FieldCondition {
	if x != nil {
		if x, ok := x.Filter.(*Filter_Field); ok {
			return x.Field
		}
	}
	return nil
}

type isFilter_Filter interface {
	isFilter_Filter()
}

type Filter_Must struct {
	Must *MustFilter `protobuf:"bytes,1,opt,name=must,proto3,oneof"`
}

type Filter_Should struct {
	Should *ShouldFilter `protobuf:"bytes,2,opt,name=should,proto3,oneof"`
}

type Filter_MustNot struct {
	MustNot *MustNotFilter `protobuf:"bytes,3,opt,name=must_not,json=mustNot,proto3,oneof"`
}

type Filter_Field struct {
	Field *FieldCondition `protobuf:"bytes,4,opt,name=field,proto3,oneof"`
}

func (*Filter_Must) isFilter_Filter() {}

func (*Filter_Should) isFilter_Filter() {}

func (*Filter_MustNot) isFilter_Filter() {}

func (*Filter_Field) isFilter_Filter() {}

type MustFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*Filter              `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MustFilter) Reset() {
	*x = MustFilter{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MustFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MustFilter) ProtoMessage() {}

func (x *MustFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MustFilter.ProtoReflect.Descriptor instead.
func (*MustFilter) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{9}
}

func (x *MustFilter) GetConditions() []*Filter {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type ShouldFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*Filter              `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShouldFilter) Reset() {
	*x = ShouldFilter{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShouldFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShouldFilter) ProtoMessage() {}

func (x *ShouldFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShouldFilter.ProtoReflect.Descriptor instead.
func (*ShouldFilter) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{10}
}

func (x *ShouldFilter) GetConditions() []*Filter {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type MustNotFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*Filter              `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MustNotFilter) Reset() {
	*x = MustNotFilter{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MustNotFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MustNotFilter) ProtoMessage() {}

func (x *MustNotFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MustNotFilter.ProtoReflect.Descriptor instead.
func (*MustNotFilter) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{11}
}

func (x *MustNotFilter) GetConditions() []*Filter {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type FieldCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Field string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Types that are valid to be assigned to Condition:
	//
	//	*FieldCondition_Match
	//	*FieldCondition_Range
	//	*FieldCondition_Values
	Condition     isFieldCondition_Condition `protobuf_oneof:"condition"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldCondition) Reset() {
	*x = FieldCondition{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldCondition) ProtoMessage() {}

func (x *FieldCondition) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldCondition.ProtoReflect.Descriptor instead.
func (*FieldCondition) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{12}
}

func (x *FieldCondition) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldCondition) GetCondition() isFieldCondition_Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *FieldCondition) GetMatch() *MatchCondition {
	if x != nil {
		if x, ok := x.Condition.(*FieldCondition_Match); ok {
			return x.Match
		}
	}
	return nil
}

func (x *FieldCondition) GetRange() *RangeCondition {
	if x != nil {
		if x, ok := x.Condition.(*FieldCondition_Range); ok {
			return x.Range
		}
	}
	return nil
}

func (x *FieldCondition) GetValues() *ValuesCondition {
	if x != nil {
		if x, ok := x.Condition.(*FieldCondition_Values); ok {
			return x.Values
		}
	}
	return nil
}

type isFieldCondition_Condition interface {
	isFieldCondition_Condition()
}

type FieldCondition_Match struct {
	Match *MatchCondition `protobuf:"bytes,2,opt,name=match,proto3,oneof"`
}

type FieldCondition_Range struct {
	Range *RangeCondition `protobuf:"bytes,3,opt,name=range,proto3,oneof"`
}

type FieldCondition_Values struct {
	Values *ValuesCondition `protobuf:"bytes,4,opt,name=values,proto3,oneof"`
}

func (*FieldCondition_Match) isFieldCondition_Condition() {}

func (*FieldCondition_Range) isFieldCondition_Condition() {}

func (*FieldCondition_Values) isFieldCondition_Condition() {}

type MatchCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Value                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCondition) Reset() {
	*x = MatchCondition{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCondition) ProtoMessage() {}

func (x *MatchCondition) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCondition.ProtoReflect.Descriptor instead.
func (*MatchCondition) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{13}
}

func (x *MatchCondition) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type RangeCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gt            *float64               `protobuf:"fixed64,1,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	Gte           *float64               `protobuf:"fixed64,2,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	Lt            *float64               `protobuf:"fixed64,3,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	Lte           *float64               `protobuf:"fixed64,4,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeCondition) Reset() {
	*x = RangeCondition{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeCondition) ProtoMessage() {}

func (x *RangeCondition) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeCondition.ProtoReflect.Descriptor instead.
func (*RangeCondition) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{14}
}

func (x *RangeCondition) GetGt() float64 {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return 0
}

func (x *RangeCondition) GetGte() float64 {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return 0
}

func (x *RangeCondition) GetLt() float64 {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return 0
}

func (x *RangeCondition) GetLte() float64 {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return 0
}

type ValuesCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValuesCondition) Reset() {
	*x = ValuesCondition{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValuesCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuesCondition) ProtoMessage() {}

func (x *ValuesCondition) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuesCondition.ProtoReflect.Descriptor instead.
func (*ValuesCondition) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{15}
}

func (x *ValuesCondition) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *CollectionConfig      `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCollectionRequest) GetConfig() *CollectionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Info          *CollectionInfo        `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCollectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateCollectionResponse) GetInfo() *CollectionInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{18}
}

func (x *GetCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *CollectionInfo        `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionResponse) Reset() {
	*x = GetCollectionResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionResponse) ProtoMessage() {}

func (x *GetCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{19}
}

func (x *GetCollectionResponse) GetInfo() *CollectionInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{20}
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*CollectionInfo      `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{21}
}

func (x *ListCollectionsResponse) GetCollections() []*CollectionInfo {
	if x != nil {
		return x.Collections
	}
	return nil
}

type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionResponse) Reset() {
	*x = DeleteCollectionResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionResponse) ProtoMessage() {}

func (x *DeleteCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteCollectionResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteCollectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpsertPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Points        []*Point               `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	Wait          bool                   `protobuf:"varint,3,opt,name=wait,proto3" json:"wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPointsRequest) Reset() {
	*x = UpsertPointsRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPointsRequest) ProtoMessage() {}

func (x *UpsertPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPointsRequest.ProtoReflect.Descriptor instead.
func (*UpsertPointsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{24}
}

func (x *UpsertPointsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *UpsertPointsRequest) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *UpsertPointsRequest) GetWait() bool {
	if x != nil {
		return x.Wait
	}
	return false
}

type UpsertPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Upserted      int32                  `protobuf:"varint,2,opt,name=upserted,proto3" json:"upserted,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPointsResponse) Reset() {
	*x = UpsertPointsResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPointsResponse) ProtoMessage() {}

func (x *UpsertPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPointsResponse.ProtoReflect.Descriptor instead.
func (*UpsertPointsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{25}
}

func (x *UpsertPointsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpsertPointsResponse) GetUpserted() int32 {
	if x != nil {
		return x.Upserted
	}
	return 0
}

func (x *UpsertPointsResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type GetPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	WithVector    bool                   `protobuf:"varint,3,opt,name=with_vector,json=withVector,proto3" json:"with_vector,omitempty"`
	WithPayload   bool                   `protobuf:"varint,4,opt,name=with_payload,json=withPayload,proto3" json:"with_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointsRequest) Reset() {
	*x = GetPointsRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointsRequest) ProtoMessage() {}

func (x *GetPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointsRequest.ProtoReflect.Descriptor instead.
func (*GetPointsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{26}
}

func (x *GetPointsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetPointsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetPointsRequest) GetWithVector() bool {
	if x != nil {
		return x.WithVector
	}
	return false
}

func (x *GetPointsRequest) GetWithPayload() bool {
	if x != nil {
		return x.WithPayload
	}
	return false
}

type GetPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointsResponse) Reset() {
	*x = GetPointsResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointsResponse) ProtoMessage() {}

func (x *GetPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointsResponse.ProtoReflect.Descriptor instead.
func (*GetPointsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{27}
}

func (x *GetPointsResponse) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type DeletePointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	Filter        *Filter                `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePointsRequest) Reset() {
	*x = DeletePointsRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePointsRequest) ProtoMessage() {}

func (x *DeletePointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePointsRequest.ProtoReflect.Descriptor instead.
func (*DeletePointsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{28}
}

func (x *DeletePointsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeletePointsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DeletePointsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type DeletePointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Deleted       int32                  `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePointsResponse) Reset() {
	*x = DeletePointsResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePointsResponse) ProtoMessage() {}

func (x *DeletePointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePointsResponse.ProtoReflect.Descriptor instead.
func (*DeletePointsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{29}
}

func (x *DeletePointsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeletePointsResponse) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

type SearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Collection     string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Vector         *Vector                `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Filter         *Filter                `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	WithVector     bool                   `protobuf:"varint,6,opt,name=with_vector,json=withVector,proto3" json:"with_vector,omitempty"`
	WithPayload    bool                   `protobuf:"varint,7,opt,name=with_payload,json=withPayload,proto3" json:"with_payload,omitempty"`
	Ef             int32                  `protobuf:"varint,8,opt,name=ef,proto3" json:"ef,omitempty"`
	ScoreThreshold float32                `protobuf:"fixed32,9,opt,name=score_threshold,json=scoreThreshold,proto3" json:"score_threshold,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{30}
}

func (x *SearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchRequest) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SearchRequest) GetWithVector() bool {
	if x != nil {
		return x.WithVector
	}
	return false
}

func (x *SearchRequest) GetWithPayload() bool {
	if x != nil {
		return x.WithPayload
	}
	return false
}

func (x *SearchRequest) GetEf() int32 {
	if x != nil {
		return x.Ef
	}
	return 0
}

func (x *SearchRequest) GetScoreThreshold() float32 {
	if x != nil {
		return x.ScoreThreshold
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScoredPoint         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TookMs        int64                  `protobuf:"varint,2,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{31}
}

func (x *SearchResponse) GetResults() []*ScoredPoint {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTookMs() int64 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

type SearchBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Vectors       []*Vector              `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter        *Filter                `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	WithVector    bool                   `protobuf:"varint,5,opt,name=with_vector,json=withVector,proto3" json:"with_vector,omitempty"`
	WithPayload   bool                   `protobuf:"varint,6,opt,name=with_payload,json=withPayload,proto3" json:"with_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBatchRequest) Reset() {
	*x = SearchBatchRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBatchRequest) ProtoMessage() {}

func (x *SearchBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBatchRequest.ProtoReflect.Descriptor instead.
func (*SearchBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{32}
}

func (x *SearchBatchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchBatchRequest) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *SearchBatchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchBatchRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SearchBatchRequest) GetWithVector() bool {
	if x != nil {
		return x.WithVector
	}
	return false
}

func (x *SearchBatchRequest) GetWithPayload() bool {
	if x != nil {
		return x.WithPayload
	}
	return false
}

type SearchBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResponse      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBatchResponse) Reset() {
	*x = SearchBatchResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBatchResponse) ProtoMessage() {}

func (x *SearchBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBatchResponse.ProtoReflect.Descriptor instead.
func (*SearchBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{33}
}

func (x *SearchBatchResponse) GetResults() []*SearchResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	PositiveIds   []string               `protobuf:"bytes,2,rep,name=positive_ids,json=positiveIds,proto3" json:"positive_ids,omitempty"`
	NegativeIds   []string               `protobuf:"bytes,3,rep,name=negative_ids,json=negativeIds,proto3" json:"negative_ids,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter        *Filter                `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	WithVector    bool                   `protobuf:"varint,6,opt,name=with_vector,json=withVector,proto3" json:"with_vector,omitempty"`
	WithPayload   bool                   `protobuf:"varint,7,opt,name=with_payload,json=withPayload,proto3" json:"with_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{34}
}

func (x *RecommendRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *RecommendRequest) GetPositiveIds() []string {
	if x != nil {
		return x.PositiveIds
	}
	return nil
}

func (x *RecommendRequest) GetNegativeIds() []string {
	if x != nil {
		return x.NegativeIds
	}
	return nil
}

func (x *RecommendRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RecommendRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *RecommendRequest) GetWithVector() bool {
	if x != nil {
		return x.WithVector
	}
	return false
}

func (x *RecommendRequest) GetWithPayload() bool {
	if x != nil {
		return x.WithPayload
	}
	return false
}

type RecommendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScoredPoint         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TookMs        int64                  `protobuf:"varint,2,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{35}
}

func (x *RecommendResponse) GetResults() []*ScoredPoint {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RecommendResponse) GetTookMs() int64 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

type ContextPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositiveId    string                 `protobuf:"bytes,1,opt,name=positive_id,json=positiveId,proto3" json:"positive_id,omitempty"`
	NegativeId    string                 `protobuf:"bytes,2,opt,name=negative_id,json=negativeId,proto3" json:"negative_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextPair) Reset() {
	*x = ContextPair{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextPair) ProtoMessage() {}

func (x *ContextPair) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextPair.ProtoReflect.Descriptor instead.
func (*ContextPair) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{36}
}

func (x *ContextPair) GetPositiveId() string {
	if x != nil {
		return x.PositiveId
	}
	return ""
}

func (x *ContextPair) GetNegativeId() string {
	if x != nil {
		return x.NegativeId
	}
	return ""
}

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Target        *Vector                `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Context       []*ContextPair         `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Filter        *Filter                `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	WithVector    bool                   `protobuf:"varint,7,opt,name=with_vector,json=withVector,proto3" json:"with_vector,omitempty"`
	WithPayload   bool                   `protobuf:"varint,8,opt,name=with_payload,json=withPayload,proto3" json:"with_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{37}
}

func (x *DiscoverRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DiscoverRequest) GetTarget() *Vector {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *DiscoverRequest) GetContext() []*ContextPair {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DiscoverRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DiscoverRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DiscoverRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DiscoverRequest) GetWithVector() bool {
	if x != nil {
		return x.WithVector
	}
	return false
}

func (x *DiscoverRequest) GetWithPayload() bool {
	if x != nil {
		return x.WithPayload
	}
	return false
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScoredPoint         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TookMs        int64                  `protobuf:"varint,2,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{38}
}

func (x *DiscoverResponse) GetResults() []*ScoredPoint {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *DiscoverResponse) GetTookMs() int64 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []string               `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{39}
}

func (x *CreateSnapshotRequest) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{40}
}

func (x *CreateSnapshotResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSnapshotResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CreateSnapshotResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{41}
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*SnapshotInfo        `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{42}
}

func (x *ListSnapshotsResponse) GetSnapshots() []*SnapshotInfo {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type SnapshotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Collections   []string               `protobuf:"bytes,4,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotInfo) Reset() {
	*x = SnapshotInfo{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfo) ProtoMessage() {}

func (x *SnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfo.ProtoReflect.Descriptor instead.
func (*SnapshotInfo) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{43}
}

func (x *SnapshotInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SnapshotInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SnapshotInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SnapshotInfo) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

type RestoreSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSnapshotRequest) Reset() {
	*x = RestoreSnapshotRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSnapshotRequest) ProtoMessage() {}

func (x *RestoreSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RestoreSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{44}
}

func (x *RestoreSnapshotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RestoreSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSnapshotResponse) Reset() {
	*x = RestoreSnapshotResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSnapshotResponse) ProtoMessage() {}

func (x *RestoreSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSnapshotResponse.ProtoReflect.Descriptor instead.
func (*RestoreSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{45}
}

func (x *RestoreSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{46}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_limyedb_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_limyedb_proto_rawDescGZIP(), []int{47}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_api_grpc_proto_limyedb_proto protoreflect.FileDescriptor

const file_api_grpc_proto_limyedb_proto_rawDesc = "" +
	"\n" +
	"\x1capi/grpc/proto/limyedb.proto\x12\alimyedb\"\x1c\n" +
	"\x06Vector\x12\x12\n" +
	"\x04data\x18\x01 \x03(\x02R\x04data\"\xc3\x01\n" +
	"\x05Point\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x06vector\x18\x02 \x01(\v2\x0f.limyedb.VectorR\x06vector\x125\n" +
	"\apayload\x18\x03 \x03(\v2\x1b.limyedb.Point.PayloadEntryR\apayload\x1aJ\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.limyedb.ValueR\x05value:\x028\x01\"\xaf\x01\n" +
	"\x05Value\x12#\n" +
	"\fnumber_value\x18\x01 \x01(\x01H\x00R\vnumberValue\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x123\n" +
	"\n" +
	"list_value\x18\x04 \x01(\v2\x12.limyedb.ListValueH\x00R\tlistValueB\x06\n" +
	"\x04kind\"3\n" +
	"\tListValue\x12&\n" +
	"\x06values\x18\x01 \x03(\v2\x0e.limyedb.ValueR\x06values\"\xe5\x01\n" +
	"\vScoredPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12'\n" +
	"\x06vector\x18\x03 \x01(\v2\x0f.limyedb.VectorR\x06vector\x12;\n" +
	"\apayload\x18\x04 \x03(\v2!.limyedb.ScoredPoint.PayloadEntryR\apayload\x1aJ\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.limyedb.ValueR\x05value:\x028\x01\"`\n" +
	"\n" +
	"HNSWConfig\x12\f\n" +
	"\x01m\x18\x01 \x01(\x05R\x01m\x12'\n" +
	"\x0fef_construction\x18\x02 \x01(\x05R\x0eefConstruction\x12\x1b\n" +
	"\tef_search\x18\x03 \x01(\x05R\befSearch\"\x9e\x01\n" +
	"\x10CollectionConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\x05R\tdimension\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x12\x17\n" +
	"\aon_disk\x18\x04 \x01(\bR\x06onDisk\x12'\n" +
	"\x04hnsw\x18\x05 \x01(\v2\x13.limyedb.HNSWConfigR\x04hnsw\"\xdf\x01\n" +
	"\x0eCollectionInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\x05R\tdimension\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x121\n" +
	"\x06config\x18\x05 \x01(\v2\x19.limyedb.CollectionConfigR\x06config\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\xd4\x01\n" +
	"\x06Filter\x12)\n" +
	"\x04must\x18\x01 \x01(\v2\x13.limyedb.MustFilterH\x00R\x04must\x12/\n" +
	"\x06should\x18\x02 \x01(\v2\x15.limyedb.ShouldFilterH\x00R\x06should\x123\n" +
	"\bmust_not\x18\x03 \x01(\v2\x16.limyedb.MustNotFilterH\x00R\amustNot\x12/\n" +
	"\x05field\x18\x04 \x01(\v2\x17.limyedb.FieldConditionH\x00R\x05fieldB\b\n" +
	"\x06filter\"=\n" +
	"\n" +
	"MustFilter\x12/\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x0f.limyedb.FilterR\n" +
	"conditions\"?\n" +
	"\fShouldFilter\x12/\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x0f.limyedb.FilterR\n" +
	"conditions\"@\n" +
	"\rMustNotFilter\x12/\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x0f.limyedb.FilterR\n" +
	"conditions\"\xc9\x01\n" +
	"\x0eFieldCondition\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12/\n" +
	"\x05match\x18\x02 \x01(\v2\x17.limyedb.MatchConditionH\x00R\x05match\x12/\n" +
	"\x05range\x18\x03 \x01(\v2\x17.limyedb.RangeConditionH\x00R\x05range\x122\n" +
	"\x06values\x18\x04 \x01(\v2\x18.limyedb.ValuesConditionH\x00R\x06valuesB\v\n" +
	"\tcondition\"6\n" +
	"\x0eMatchCondition\x12$\n" +
	"\x05value\x18\x01 \x01(\v2\x0e.limyedb.ValueR\x05value\"\x86\x01\n" +
	"\x0eRangeCondition\x12\x13\n" +
	"\x02gt\x18\x01 \x01(\x01H\x00R\x02gt\x88\x01\x01\x12\x15\n" +
	"\x03gte\x18\x02 \x01(\x01H\x01R\x03gte\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x03 \x01(\x01H\x02R\x02lt\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x04 \x01(\x01H\x03R\x03lte\x88\x01\x01B\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lte\"9\n" +
	"\x0fValuesCondition\x12&\n" +
	"\x06values\x18\x01 \x03(\v2\x0e.limyedb.ValueR\x06values\"L\n" +
	"\x17CreateCollectionRequest\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.limyedb.CollectionConfigR\x06config\"a\n" +
	"\x18CreateCollectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x04info\x18\x02 \x01(\v2\x17.limyedb.CollectionInfoR\x04info\"*\n" +
	"\x14GetCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\x15GetCollectionResponse\x12+\n" +
	"\x04info\x18\x01 \x01(\v2\x17.limyedb.CollectionInfoR\x04info\"\x18\n" +
	"\x16ListCollectionsRequest\"T\n" +
	"\x17ListCollectionsResponse\x129\n" +
	"\vcollections\x18\x01 \x03(\v2\x17.limyedb.CollectionInfoR\vcollections\"-\n" +
	"\x17DeleteCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"4\n" +
	"\x18DeleteCollectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"q\n" +
	"\x13UpsertPointsRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12&\n" +
	"\x06points\x18\x02 \x03(\v2\x0e.limyedb.PointR\x06points\x12\x12\n" +
	"\x04wait\x18\x03 \x01(\bR\x04wait\"d\n" +
	"\x14UpsertPointsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bupserted\x18\x02 \x01(\x05R\bupserted\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"\x88\x01\n" +
	"\x10GetPointsRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\x12\x1f\n" +
	"\vwith_vector\x18\x03 \x01(\bR\n" +
	"withVector\x12!\n" +
	"\fwith_payload\x18\x04 \x01(\bR\vwithPayload\";\n" +
	"\x11GetPointsResponse\x12&\n" +
	"\x06points\x18\x01 \x03(\v2\x0e.limyedb.PointR\x06points\"p\n" +
	"\x13DeletePointsRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\x12'\n" +
	"\x06filter\x18\x03 \x01(\v2\x0f.limyedb.FilterR\x06filter\"J\n" +
	"\x14DeletePointsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\x05R\adeleted\"\xac\x02\n" +
	"\rSearchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12'\n" +
	"\x06vector\x18\x02 \x01(\v2\x0f.limyedb.VectorR\x06vector\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12'\n" +
	"\x06filter\x18\x05 \x01(\v2\x0f.limyedb.FilterR\x06filter\x12\x1f\n" +
	"\vwith_vector\x18\x06 \x01(\bR\n" +
	"withVector\x12!\n" +
	"\fwith_payload\x18\a \x01(\bR\vwithPayload\x12\x0e\n" +
	"\x02ef\x18\b \x01(\x05R\x02ef\x12'\n" +
	"\x0fscore_threshold\x18\t \x01(\x02R\x0escoreThreshold\"Y\n" +
	"\x0eSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.limyedb.ScoredPointR\aresults\x12\x17\n" +
	"\atook_ms\x18\x02 \x01(\x03R\x06tookMs\"\xe2\x01\n" +
	"\x12SearchBatchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12)\n" +
	"\avectors\x18\x02 \x03(\v2\x0f.limyedb.VectorR\avectors\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12'\n" +
	"\x06filter\x18\x04 \x01(\v2\x0f.limyedb.FilterR\x06filter\x12\x1f\n" +
	"\vwith_vector\x18\x05 \x01(\bR\n" +
	"withVector\x12!\n" +
	"\fwith_payload\x18\x06 \x01(\bR\vwithPayload\"H\n" +
	"\x13SearchBatchResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.limyedb.SearchResponseR\aresults\"\xfb\x01\n" +
	"\x10RecommendRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12!\n" +
	"\fpositive_ids\x18\x02 \x03(\tR\vpositiveIds\x12!\n" +
	"\fnegative_ids\x18\x03 \x03(\tR\vnegativeIds\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12'\n" +
	"\x06filter\x18\x05 \x01(\v2\x0f.limyedb.FilterR\x06filter\x12\x1f\n" +
	"\vwith_vector\x18\x06 \x01(\bR\n" +
	"withVector\x12!\n" +
	"\fwith_payload\x18\a \x01(\bR\vwithPayload\"\\\n" +
	"\x11RecommendResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.limyedb.ScoredPointR\aresults\x12\x17\n" +
	"\atook_ms\x18\x02 \x01(\x03R\x06tookMs\"O\n" +
	"\vContextPair\x12\x1f\n" +
	"\vpositive_id\x18\x01 \x01(\tR\n" +
	"positiveId\x12\x1f\n" +
	"\vnegative_id\x18\x02 \x01(\tR\n" +
	"negativeId\"\xa5\x02\n" +
	"\x0fDiscoverRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12'\n" +
	"\x06target\x18\x02 \x01(\v2\x0f.limyedb.VectorR\x06target\x12.\n" +
	"\acontext\x18\x03 \x03(\v2\x14.limyedb.ContextPairR\acontext\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12'\n" +
	"\x06filter\x18\x06 \x01(\v2\x0f.limyedb.FilterR\x06filter\x12\x1f\n" +
	"\vwith_vector\x18\a \x01(\bR\n" +
	"withVector\x12!\n" +
	"\fwith_payload\x18\b \x01(\bR\vwithPayload\"[\n" +
	"\x10DiscoverResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.limyedb.ScoredPointR\aresults\x12\x17\n" +
	"\atook_ms\x18\x02 \x01(\x03R\x06tookMs\"9\n" +
	"\x15CreateSnapshotRequest\x12 \n" +
	"\vcollections\x18\x01 \x03(\tR\vcollections\"Z\n" +
	"\x16CreateSnapshotResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\x16\n" +
	"\x14ListSnapshotsRequest\"L\n" +
	"\x15ListSnapshotsResponse\x123\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x15.limyedb.SnapshotInfoR\tsnapshots\"r\n" +
	"\fSnapshotInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12 \n" +
	"\vcollections\x18\x04 \x03(\tR\vcollections\"(\n" +
	"\x16RestoreSnapshotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x17RestoreSnapshotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xd2\t\n" +
	"\aLimyeDB\x12W\n" +
	"\x10CreateCollection\x12 .limyedb.CreateCollectionRequest\x1a!.limyedb.CreateCollectionResponse\x12N\n" +
	"\rGetCollection\x12\x1d.limyedb.GetCollectionRequest\x1a\x1e.limyedb.GetCollectionResponse\x12T\n" +
	"\x0fListCollections\x12\x1f.limyedb.ListCollectionsRequest\x1a .limyedb.ListCollectionsResponse\x12W\n" +
	"\x10DeleteCollection\x12 .limyedb.DeleteCollectionRequest\x1a!.limyedb.DeleteCollectionResponse\x12K\n" +
	"\fUpsertPoints\x12\x1c.limyedb.UpsertPointsRequest\x1a\x1d.limyedb.UpsertPointsResponse\x12B\n" +
	"\tGetPoints\x12\x19.limyedb.GetPointsRequest\x1a\x1a.limyedb.GetPointsResponse\x12K\n" +
	"\fDeletePoints\x12\x1c.limyedb.DeletePointsRequest\x1a\x1d.limyedb.DeletePointsResponse\x12S\n" +
	"\x12StreamUpsertPoints\x12\x1c.limyedb.UpsertPointsRequest\x1a\x1d.limyedb.UpsertPointsResponse(\x01\x129\n" +
	"\x06Search\x12\x16.limyedb.SearchRequest\x1a\x17.limyedb.SearchResponse\x12H\n" +
	"\vSearchBatch\x12\x1b.limyedb.SearchBatchRequest\x1a\x1c.limyedb.SearchBatchResponse\x12B\n" +
	"\tRecommend\x12\x19.limyedb.RecommendRequest\x1a\x1a.limyedb.RecommendResponse\x12?\n" +
	"\bDiscover\x12\x18.limyedb.DiscoverRequest\x1a\x19.limyedb.DiscoverResponse\x12Q\n" +
	"\x0eCreateSnapshot\x12\x1e.limyedb.CreateSnapshotRequest\x1a\x1f.limyedb.CreateSnapshotResponse\x12N\n" +
	"\rListSnapshots\x12\x1d.limyedb.ListSnapshotsRequest\x1a\x1e.limyedb.ListSnapshotsResponse\x12T\n" +
	"\x0fRestoreSnapshot\x12\x1f.limyedb.RestoreSnapshotRequest\x1a .limyedb.RestoreSnapshotResponse\x129\n" +
	"\x06Health\x12\x16.limyedb.HealthRequest\x1a\x17.limyedb.HealthResponseB+Z)github.com/limyedb/limyedb/api/grpc/protob\x06proto3"

var (
	file_api_grpc_proto_limyedb_proto_rawDescOnce sync.Once
	file_api_grpc_proto_limyedb_proto_rawDescData []byte
)

func file_api_grpc_proto_limyedb_proto_rawDescGZIP() []byte {
	file_api_grpc_proto_limyedb_proto_rawDescOnce.Do(func() {
		file_api_grpc_proto_limyedb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_proto_limyedb_proto_rawDesc), len(file_api_grpc_proto_limyedb_proto_rawDesc)))
	})
	return file_api_grpc_proto_limyedb_proto_rawDescData
}

var file_api_grpc_proto_limyedb_proto_msgTypes = make([]protoimpl.MessageInfo, 50)
var file_api_grpc_proto_limyedb_proto_goTypes = []any{
	(*Vector)(nil),                   // 0: limyedb.Vector
	(*Point)(nil),                    // 1: limyedb.Point
	(*Value)(nil),                    // 2: limyedb.Value
	(*ListValue)(nil),                // 3: limyedb.ListValue
	(*ScoredPoint)(nil),              // 4: limyedb.ScoredPoint
	(*HNSWConfig)(nil),               // 5: limyedb.HNSWConfig
	(*CollectionConfig)(nil),         // 6: limyedb.CollectionConfig
	(*CollectionInfo)(nil),           // 7: limyedb.CollectionInfo
	(*Filter)(nil),                   // 8: limyedb.Filter
	(*MustFilter)(nil),               // 9: limyedb.MustFilter
	(*ShouldFilter)(nil),             // 10: limyedb.ShouldFilter
	(*MustNotFilter)(nil),            // 11: limyedb.MustNotFilter
	(*FieldCondition)(nil),           // 12: limyedb.FieldCondition
	(*MatchCondition)(nil),           // 13: limyedb.MatchCondition
	(*RangeCondition)(nil),           // 14: limyedb.RangeCondition
	(*ValuesCondition)(nil),          // 15: limyedb.ValuesCondition
	(*CreateCollectionRequest)(nil),  // 16: limyedb.CreateCollectionRequest
	(*CreateCollectionResponse)(nil), // 17: limyedb.CreateCollectionResponse
	(*GetCollectionRequest)(nil),     // 18: limyedb.GetCollectionRequest
	(*GetCollectionResponse)(nil),    // 19: limyedb.GetCollectionResponse
	(*ListCollectionsRequest)(nil),   // 20: limyedb.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),  // 21: limyedb.ListCollectionsResponse
	(*DeleteCollectionRequest)(nil),  // 22: limyedb.DeleteCollectionRequest
	(*DeleteCollectionResponse)(nil), // 23: limyedb.DeleteCollectionResponse
	(*UpsertPointsRequest)(nil),      // 24: limyedb.UpsertPointsRequest
	(*UpsertPointsResponse)(nil),     // 25: limyedb.UpsertPointsResponse
	(*GetPointsRequest)(nil),         // 26: limyedb.GetPointsRequest
	(*GetPointsResponse)(nil),        // 27: limyedb.GetPointsResponse
	(*DeletePointsRequest)(nil),      // 28: limyedb.DeletePointsRequest
	(*DeletePointsResponse)(nil),     // 29: limyedb.DeletePointsResponse
	(*SearchRequest)(nil),            // 30: limyedb.SearchRequest
	(*SearchResponse)(nil),           // 31: limyedb.SearchResponse
	(*SearchBatchRequest)(nil),       // 32: limyedb.SearchBatchRequest
	(*SearchBatchResponse)(nil),      // 33: limyedb.SearchBatchResponse
	(*RecommendRequest)(nil),         // 34: limyedb.RecommendRequest
	(*RecommendResponse)(nil),        // 35: limyedb.RecommendResponse
	(*ContextPair)(nil),              // 36: limyedb.ContextPair
	(*DiscoverRequest)(nil),          // 37: limyedb.DiscoverRequest
	(*DiscoverResponse)(nil),         // 38: limyedb.DiscoverResponse
	(*CreateSnapshotRequest)(nil),    // 39: limyedb.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),   // 40: limyedb.CreateSnapshotResponse
	(*ListSnapshotsRequest)(nil),     // 41: limyedb.ListSnapshotsRequest
	(*ListSnapshotsResponse)(nil),    // 42: limyedb.ListSnapshotsResponse
	(*SnapshotInfo)(nil),             // 43: limyedb.SnapshotInfo
	(*RestoreSnapshotRequest)(nil),   // 44: limyedb.RestoreSnapshotRequest
	(*RestoreSnapshotResponse)(nil),  // 45: limyedb.RestoreSnapshotResponse
	(*HealthRequest)(nil),            // 46: limyedb.HealthRequest
	(*HealthResponse)(nil),           // 47: limyedb.HealthResponse
	nil,                              // 48: limyedb.Point.PayloadEntry
	nil,                              // 49: limyedb.ScoredPoint.PayloadEntry
}
var file_api_grpc_proto_limyedb_proto_depIdxs = []int32{
	0,  // 0: limyedb.Point.vector:type_name -> limyedb.Vector
	48, // 1: limyedb.Point.payload:type_name -> limyedb.Point.PayloadEntry
	3,  // 2: limyedb.Value.list_value:type_name -> limyedb.ListValue
	2,  // 3: limyedb.ListValue.values:type_name -> limyedb.Value
	0,  // 4: limyedb.ScoredPoint.vector:type_name -> limyedb.Vector
	49, // 5: limyedb.ScoredPoint.payload:type_name -> limyedb.ScoredPoint.PayloadEntry
	5,  // 6: limyedb.CollectionConfig.hnsw:type_name -> limyedb.HNSWConfig
	6,  // 7: limyedb.CollectionInfo.config:type_name -> limyedb.CollectionConfig
	9,  // 8: limyedb.Filter.must:type_name -> limyedb.MustFilter
	10, // 9: limyedb.Filter.should:type_name -> limyedb.ShouldFilter
	11, // 10: limyedb.Filter.must_not:type_name -> limyedb.MustNotFilter
	12, // 11: limyedb.Filter.field:type_name -> limyedb.FieldCondition
	8,  // 12: limyedb.MustFilter.conditions:type_name -> limyedb.Filter
	8,  // 13: limyedb.ShouldFilter.conditions:type_name -> limyedb.Filter
	8,  // 14: limyedb.MustNotFilter.conditions:type_name -> limyedb.Filter
	13, // 15: limyedb.FieldCondition.match:type_name -> limyedb.MatchCondition
	14, // 16: limyedb.FieldCondition.range:type_name -> limyedb.RangeCondition
	15, // 17: limyedb.FieldCondition.values:type_name -> limyedb.ValuesCondition
	2,  // 18: limyedb.MatchCondition.value:type_name -> limyedb.Value
	2,  // 19: limyedb.ValuesCondition.values:type_name -> limyedb.Value
	6,  // 20: limyedb.CreateCollectionRequest.config:type_name -> limyedb.CollectionConfig
	7,  // 21: limyedb.CreateCollectionResponse.info:type_name -> limyedb.CollectionInfo
	7,  // 22: limyedb.GetCollectionResponse.info:type_name -> limyedb.CollectionInfo
	7,  // 23: limyedb.ListCollectionsResponse.collections:type_name -> limyedb.CollectionInfo
	1,  // 24: limyedb.UpsertPointsRequest.points:type_name -> limyedb.Point
	1,  // 25: limyedb.GetPointsResponse.points:type_name -> limyedb.Point
	8,  // 26: limyedb.DeletePointsRequest.filter:type_name -> limyedb.Filter
	0,  // 27: limyedb.SearchRequest.vector:type_name -> limyedb.Vector
	8,  // 28: limyedb.SearchRequest.filter:type_name -> limyedb.Filter
	4,  // 29: limyedb.SearchResponse.results:type_name -> limyedb.ScoredPoint
	0,  // 30: limyedb.SearchBatchRequest.vectors:type_name -> limyedb.Vector
	8,  // 31: limyedb.SearchBatchRequest.filter:type_name -> limyedb.Filter
	31, // 32: limyedb.SearchBatchResponse.results:type_name -> limyedb.SearchResponse
	8,  // 33: limyedb.RecommendRequest.filter:type_name -> limyedb.Filter
	4,  // 34: limyedb.RecommendResponse.results:type_name -> limyedb.ScoredPoint
	0,  // 35: limyedb.DiscoverRequest.target:type_name -> limyedb.Vector
	36, // 36: limyedb.DiscoverRequest.context:type_name -> limyedb.ContextPair
	8,  // 37: limyedb.DiscoverRequest.filter:type_name -> limyedb.Filter
	4,  // 38: limyedb.DiscoverResponse.results:type_name -> limyedb.ScoredPoint
	43, // 39: limyedb.ListSnapshotsResponse.snapshots:type_name -> limyedb.SnapshotInfo
	2,  // 40: limyedb.Point.PayloadEntry.value:type_name -> limyedb.Value
	2,  // 41: limyedb.ScoredPoint.PayloadEntry.value:type_name -> limyedb.Value
	16, // 42: limyedb.LimyeDB.CreateCollection:input_type -> limyedb.CreateCollectionRequest
	18, // 43: limyedb.LimyeDB.GetCollection:input_type -> limyedb.GetCollectionRequest
	20, // 44: limyedb.LimyeDB.ListCollections:input_type -> limyedb.ListCollectionsRequest
	22, // 45: limyedb.LimyeDB.DeleteCollection:input_type -> limyedb.DeleteCollectionRequest
	24, // 46: limyedb.LimyeDB.UpsertPoints:input_type -> limyedb.UpsertPointsRequest
	26, // 47: limyedb.LimyeDB.GetPoints:input_type -> limyedb.GetPointsRequest
	28, // 48: limyedb.LimyeDB.DeletePoints:input_type -> limyedb.DeletePointsRequest
	24, // 49: limyedb.LimyeDB.StreamUpsertPoints:input_type -> limyedb.UpsertPointsRequest
	30, // 50: limyedb.LimyeDB.Search:input_type -> limyedb.SearchRequest
	32, // 51: limyedb.LimyeDB.SearchBatch:input_type -> limyedb.SearchBatchRequest
	34, // 52: limyedb.LimyeDB.Recommend:input_type -> limyedb.RecommendRequest
	37, // 53: limyedb.LimyeDB.Discover:input_type -> limyedb.DiscoverRequest
	39, // 54: limyedb.LimyeDB.CreateSnapshot:input_type -> limyedb.CreateSnapshotRequest
	41, // 55: limyedb.LimyeDB.ListSnapshots:input_type -> limyedb.ListSnapshotsRequest
	44, // 56: limyedb.LimyeDB.RestoreSnapshot:input_type -> limyedb.RestoreSnapshotRequest
	46, // 57: limyedb.LimyeDB.Health:input_type -> limyedb.HealthRequest
	17, // 58: limyedb.LimyeDB.CreateCollection:output_type -> limyedb.CreateCollectionResponse
	19, // 59: limyedb.LimyeDB.GetCollection:output_type -> limyedb.GetCollectionResponse
	21, // 60: limyedb.LimyeDB.ListCollections:output_type -> limyedb.ListCollectionsResponse
	23, // 61: limyedb.LimyeDB.DeleteCollection:output_type -> limyedb.DeleteCollectionResponse
	25, // 62: limyedb.LimyeDB.UpsertPoints:output_type -> limyedb.UpsertPointsResponse
	27, // 63: limyedb.LimyeDB.GetPoints:output_type -> limyedb.GetPointsResponse
	29, // 64: limyedb.LimyeDB.DeletePoints:output_type -> limyedb.DeletePointsResponse
	25, // 65: limyedb.LimyeDB.StreamUpsertPoints:output_type -> limyedb.UpsertPointsResponse
	31, // 66: limyedb.LimyeDB.Search:output_type -> limyedb.SearchResponse
	33, // 67: limyedb.LimyeDB.SearchBatch:output_type -> limyedb.SearchBatchResponse
	35, // 68: limyedb.LimyeDB.Recommend:output_type -> limyedb.RecommendResponse
	38, // 69: limyedb.LimyeDB.Discover:output_type -> limyedb.DiscoverResponse
	40, // 70: limyedb.LimyeDB.CreateSnapshot:output_type -> limyedb.CreateSnapshotResponse
	42, // 71: limyedb.LimyeDB.ListSnapshots:output_type -> limyedb.ListSnapshotsResponse
	45, // 72: limyedb.LimyeDB.RestoreSnapshot:output_type -> limyedb.RestoreSnapshotResponse
	47, // 73: limyedb.LimyeDB.Health:output_type -> limyedb.HealthResponse
	58, // [58:74] is the sub-list for method output_type
	42, // [42:58] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_limyedb_proto_init() }
func file_api_grpc_proto_limyedb_proto_init() {
	if File_api_grpc_proto_limyedb_proto != nil {
		return
	}
	file_api_grpc_proto_limyedb_proto_msgTypes[2].OneofWrappers = []any{
		(*Value_NumberValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_ListValue)(nil),
	}
	file_api_grpc_proto_limyedb_proto_msgTypes[8].OneofWrappers = []any{
		(*Filter_Must)(nil),
		(*Filter_Should)(nil),
		(*Filter_MustNot)(nil),
		(*Filter_Field)(nil),
	}
	file_api_grpc_proto_limyedb_proto_msgTypes[12].OneofWrappers = []any{
		(*FieldCondition_Match)(nil),
		(*FieldCondition_Range)(nil),
		(*FieldCondition_Values)(nil),
	}
	file_api_grpc_proto_limyedb_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_proto_limyedb_proto_rawDesc), len(file_api_grpc_proto_limyedb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   50,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_proto_limyedb_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_limyedb_proto_depIdxs,
		MessageInfos:      file_api_grpc_proto_limyedb_proto_msgTypes,
	}.Build()
	File_api_grpc_proto_limyedb_proto = out.File
	file_api_grpc_proto_limyedb_proto_goTypes = nil
	file_api_grpc_proto_limyedb_proto_depIdxs = nil
}
