import re

path = '/Users/loreste/limye/limyedb/api/grpc/service.go'
with open(path, 'r') as f:
    orig_content = f.read()

content = orig_content

# Add import
content = content.replace('"github.com/limyedb/limyedb/pkg/storage/snapshot"', '"github.com/limyedb/limyedb/pkg/storage/snapshot"\n\tpb "github.com/limyedb/limyedb/api/grpc/proto"')

# Replace UnimplementedLimyeDBServer with pb.UnimplementedLimyeDBServer inside the struct
content = content.replace("UnimplementedLimyeDBServer\n}", "pb.UnimplementedLimyeDBServer\n}")

# Remove the manual Unimplemented methods
content = re.sub(r'// UnimplementedLimyeDBServer provides default implementations\ntype UnimplementedLimyeDBServer struct\{\}\n\n(?:func \(UnimplementedLimyeDBServer\) .*\{\n(?:\treturn .*\n)*\}\n)*(?:func \(UnimplementedLimyeDBServer\) mustEmbedUnimplementedLimyeDBServer\(\) \{\}\n)?', '', content)

proto_types = [
    "CreateCollectionRequest", "CreateCollectionResponse",
    "GetCollectionRequest", "GetCollectionResponse",
    "ListCollectionsRequest", "ListCollectionsResponse",
    "DeleteCollectionRequest", "DeleteCollectionResponse",
    "UpsertPointsRequest", "UpsertPointsResponse",
    "GetPointsRequest", "GetPointsResponse",
    "DeletePointsRequest", "DeletePointsResponse",
    "SearchRequest", "SearchResponse",
    "SearchBatchRequest", "SearchBatchResponse",
    "RecommendRequest", "RecommendResponse",
    "ContextPair",
    "DiscoverRequest", "DiscoverResponse",
    "CreateSnapshotRequest", "CreateSnapshotResponse",
    "ListSnapshotsRequest", "ListSnapshotsResponse",
    "RestoreSnapshotRequest", "RestoreSnapshotResponse",
    "HealthRequest", "HealthResponse",
    "Point", "Vector", "ScoredPoint", "Value", "CollectionInfo", "SnapshotInfo",
    "Filter", "Condition", "CollectionConfig", "Match", "Range", "HNSWConfig"
]

for p in proto_types:
    # Match EXACTLY if it's NOT preceded by a word char or a dot.
    pattern = r'(?<![\w\.])' + p + r'\b'
    content = re.sub(pattern, 'pb.' + p, content)

# Value_NumberValue -> pb.Value_NumberValue
content = re.sub(r'(?<![\w\.])Value_NumberValue\b', 'pb.Value_NumberValue', content)
content = re.sub(r'(?<![\w\.])Value_StringValue\b', 'pb.Value_StringValue', content)
content = re.sub(r'(?<![\w\.])Value_BoolValue\b', 'pb.Value_BoolValue', content)

content = content.replace("LimyeDB_StreamUpsertPointsServer", "pb.LimyeDB_StreamUpsertPointsServer")

# Remove the manually defined structs starting at line 691 onwards
msg_index = content.find('// Message types (these would normally be generated by protoc)')
if msg_index != -1:
    content = content[:msg_index]

with open(path, 'w') as f:
    f.write(content)

print("Refactored service.go successfully")
