package grpc

import (
	"context"
	"net"

	"google.golang.org/grpc"
	"google.golang.org/grpc/keepalive"
	"google.golang.org/grpc/reflection"
	"time"

	"github.com/limyedb/limyedb/pkg/collection"
	"github.com/limyedb/limyedb/pkg/config"
	"github.com/limyedb/limyedb/pkg/storage/snapshot"
)

// Server represents the gRPC server
type Server struct {
	grpcServer  *grpc.Server
	config      *config.ServerConfig
	collections *collection.Manager
	snapshots   *snapshot.Manager
	listener    net.Listener
}

// NewServer creates a new gRPC server
func NewServer(cfg *config.ServerConfig, collections *collection.Manager, snapshots *snapshot.Manager) *Server {
	// Create gRPC server with options
	opts := []grpc.ServerOption{
		grpc.MaxRecvMsgSize(int(cfg.MaxRequestSize)),
		grpc.MaxSendMsgSize(int(cfg.MaxRequestSize)),
		grpc.KeepaliveParams(keepalive.ServerParameters{
			MaxConnectionIdle:     15 * time.Minute, // Evict idle connections to prevent memory starvation
			MaxConnectionAge:      30 * time.Minute, // Aggressively cycle connections checking load balancers scaling
			MaxConnectionAgeGrace: 5 * time.Minute,
			Time:                  5 * time.Minute,  // Ping the client if idle 
			Timeout:               1 * time.Second,  // Wait 1 second for ping back
		}),
	}

	grpcServer := grpc.NewServer(opts...)

	s := &Server{
		grpcServer:  grpcServer,
		config:      cfg,
		collections: collections,
		snapshots:   snapshots,
	}

	// Register service
	service := NewLimyeDBService(collections, snapshots)
	RegisterLimyeDBServer(grpcServer, service)

	// Enable reflection for debugging
	reflection.Register(grpcServer)

	return s
}

// Start starts the gRPC server
func (s *Server) Start() error {
	listener, err := net.Listen("tcp", s.config.GRPCAddress)
	if err != nil {
		return err
	}
	s.listener = listener

	return s.grpcServer.Serve(listener)
}

// Stop gracefully stops the gRPC server
func (s *Server) Stop() {
	s.grpcServer.GracefulStop()
	if s.listener != nil {
		_ = s.listener.Close() // Error intentionally ignored during shutdown
	}
}

// LimyeDBServer interface (generated by protoc)
type LimyeDBServer interface {
	CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error)
	GetCollection(context.Context, *GetCollectionRequest) (*GetCollectionResponse, error)
	ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error)
	DeleteCollection(context.Context, *DeleteCollectionRequest) (*DeleteCollectionResponse, error)
	UpsertPoints(context.Context, *UpsertPointsRequest) (*UpsertPointsResponse, error)
	GetPoints(context.Context, *GetPointsRequest) (*GetPointsResponse, error)
	DeletePoints(context.Context, *DeletePointsRequest) (*DeletePointsResponse, error)
	StreamUpsertPoints(LimyeDB_StreamUpsertPointsServer) error
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	SearchBatch(context.Context, *SearchBatchRequest) (*SearchBatchResponse, error)
	Recommend(context.Context, *RecommendRequest) (*RecommendResponse, error)
	Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*RestoreSnapshotResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedLimyeDBServer()
}

// LimyeDB_StreamUpsertPointsServer interface for streaming
type LimyeDB_StreamUpsertPointsServer interface {
	SendAndClose(*UpsertPointsResponse) error
	Recv() (*UpsertPointsRequest, error)
	grpc.ServerStream
}

// RegisterLimyeDBServer registers the LimyeDB service
func RegisterLimyeDBServer(s *grpc.Server, srv LimyeDBServer) {
	s.RegisterService(&LimyeDB_ServiceDesc, srv)
}

// LimyeDB_ServiceDesc is the grpc.ServiceDesc for LimyeDB service
var LimyeDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "limyedb.LimyeDB",
	HandlerType: (*LimyeDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _LimyeDB_CreateCollection_Handler,
		},
		{
			MethodName: "GetCollection",
			Handler:    _LimyeDB_GetCollection_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _LimyeDB_ListCollections_Handler,
		},
		{
			MethodName: "DeleteCollection",
			Handler:    _LimyeDB_DeleteCollection_Handler,
		},
		{
			MethodName: "UpsertPoints",
			Handler:    _LimyeDB_UpsertPoints_Handler,
		},
		{
			MethodName: "GetPoints",
			Handler:    _LimyeDB_GetPoints_Handler,
		},
		{
			MethodName: "DeletePoints",
			Handler:    _LimyeDB_DeletePoints_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _LimyeDB_Search_Handler,
		},
		{
			MethodName: "SearchBatch",
			Handler:    _LimyeDB_SearchBatch_Handler,
		},
		{
			MethodName: "Recommend",
			Handler:    _LimyeDB_Recommend_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _LimyeDB_Discover_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _LimyeDB_CreateSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _LimyeDB_ListSnapshots_Handler,
		},
		{
			MethodName: "RestoreSnapshot",
			Handler:    _LimyeDB_RestoreSnapshot_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _LimyeDB_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUpsertPoints",
			Handler:       _LimyeDB_StreamUpsertPoints_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "limyedb.proto",
}

// Handler implementations

func _LimyeDB_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/CreateCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).CreateCollection(ctx, req.(*CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_GetCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).GetCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/GetCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).GetCollection(ctx, req.(*GetCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/ListCollections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).ListCollections(ctx, req.(*ListCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_DeleteCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).DeleteCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/DeleteCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).DeleteCollection(ctx, req.(*DeleteCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_UpsertPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).UpsertPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/UpsertPoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).UpsertPoints(ctx, req.(*UpsertPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_GetPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).GetPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/GetPoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).GetPoints(ctx, req.(*GetPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_DeletePoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).DeletePoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/DeletePoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).DeletePoints(ctx, req.(*DeletePointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_StreamUpsertPoints_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LimyeDBServer).StreamUpsertPoints(&limyeDBStreamUpsertPointsServer{stream})
}

type limyeDBStreamUpsertPointsServer struct {
	grpc.ServerStream
}

func (x *limyeDBStreamUpsertPointsServer) SendAndClose(m *UpsertPointsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *limyeDBStreamUpsertPointsServer) Recv() (*UpsertPointsRequest, error) {
	m := new(UpsertPointsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _LimyeDB_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_SearchBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).SearchBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/SearchBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).SearchBatch(ctx, req.(*SearchBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_Recommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).Recommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/Recommend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).Recommend(ctx, req.(*RecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/Discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/CreateSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/ListSnapshots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_RestoreSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).RestoreSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/RestoreSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).RestoreSnapshot(ctx, req.(*RestoreSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimyeDB_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimyeDBServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/limyedb.LimyeDB/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimyeDBServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}
